### ISSUE TITLE
lcg-cp is hardcoded for slc6

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#129]
We currently have the OSG setup [hard-coded](https://github.com/matz-e/lobster/blob/master/lobster/cmssw/data/wrapper.sh#L123) for slc6. This causes srm stageout to fail if the user is running cmssw compiled on slc5. Switching `el6-$(uname -m)` to `el5-$(uname -m)` solves the problem. Do we want to figure out a way to determine the correct setup script based on the cmssw version rather than the machine? It might also make sense to say 'slc5 code is not supported, if you want to run crappy old code it's your own responsibility to hack the wrapper'.

    /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.2/3.2.23/el6-x86_64/usr/bin/lcg-cp: /cvmfs/cms.cern.ch/slc5_amd64_gcc462/cms/cmssw/CMSSW_5_2_5/external/slc5_amd64_gcc462/lib/libuuid.so.1: version `UUID_1.0' not found (required by /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.2/3.2.23/el6-x86_64/usr/lib64/libgfal.so.1)

**Comment by klannon** [comment]
Do you have a problem while trying to run lcg-cp on earth with an SLC5 release set up?  I'm trying to understand why this hasn't been encountered before.

In general, I'm not in favor of doing anything that, for example, involves trying to make Lobster guess the right version (SLC5, 6, etc.) based on the name of the CMSSW release.  On the other hand, it would be nice to avoid having anything related to the version of SLC (or really RH) hard-coded since we know that this will change with time.  I would have assumed that the right thing to do would be to setup the version of OSG that corresponds to the OS version of the node we're running on.  (E.g. RH6 worker sets up el6 while a RH5 worker would try to set up el5.  Some day, the RH7 workers would set up el7, etc., ...)

Thoughts?

**Comment by annawoodard** [comment]
I have the problem unless I source the slc5 setup script. I think it's because cmssw puts its own version of some required libraries in your path, so if you will have a mismatch: you are running the version of lcg-cp corresponding to the machine OS, but you will get the library corresponding to the cmssw-compiled OS.

    CMSSW_5_2_5/src > cmsenv
    CMSSW_5_2_5/src > lcg-cp -b -v -D srmv2 file:////afs/crc.nd.edu/user/a/awoodard/releases/event_generation/CMSSW_5_2_5/src/spam srm://ndcms.crc.nd.edu:8443/srm/v2/server?SFN=/hadoop/store/user/awoodard/more_spam
    lcg-cp: /cvmfs/cms.cern.ch/slc5_amd64_gcc462/cms/cmssw/CMSSW_5_2_5/external/slc5_amd64_gcc462/lib/libuuid.so.1: version `UUID_1.0' not found (required by /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.1/3.1.46/el6-x86_64/usr/lib64/libgfal.so.1)
    CMSSW_5_2_5/src > source /cvmfs/oasis.opensciencegrid.org/osg-software/osg-wn-client/3.2/current/el5-x86_64/setup.sh
    CMSSW_5_2_5/src > lcg-cp -b -v -D srmv2 file:////afs/crc.nd.edu/user/a/awoodard/releases/event_generation/CMSSW_5_2_5/src/spam srm://ndcms.crc.nd.edu:8443/srm/v2/server?SFN=/hadoop/store/user/awoodard/more_spam
    [...]
    Transfer took 1010 ms

**Comment by klannon** [comment]
Presumably, if you never do "cmsenv" it's also fine, right?  Is the correct solution just to isolate the environment used to run the CMS job from the environment used for stageout?

**Comment by annawoodard** [comment]
Good point— I see now that I’m going in circles. I already addressed this issue, but the change got lost. I've tested that it solves the issue and opened a PR.

**Comment by annawoodard** [comment]
Note that this removes the hard-coded SLC version piece by parsing from /etc/redhat-release (not the cmssw version.)
