### ISSUE TITLE
Upload the job log to dashboard?

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#138]
CRAB supposedly does this in some cases.  We could splice the executable log into the job log and do the same…

**Comment by khurtado** [comment]
Does this require the log files to be accessible via some web server?

**Comment by annawoodard** [comment]
IMHO our way of presenting logs and plotting in general is more suited to our needs and faster than the dashboard. We need to get the reporting right so that dashboard is counting us correctly, but I would vote we don't spend too much effort beyond that on supporting two different but overlapping monitoring approaches.

**Comment by matz-e** [comment]
Good point.  I was just checking the dashboard reporting on some of my jobs and noticed the lack of logs… sometimes I think it is nice to have logs of completed jobs at hand, too.

@khurtado yes, I think there might be a web server involved, too.
