### ISSUE TITLE
Remove Notre Dame specific hard-coded bits

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#15]
The following are hard-coded and should be configurable:

* `parrot` binary
* the local site `T3_US_NotreDame`
* the http proxy

We should make these either configurable via the master or pass them along in the environment of `condor_submit_workers`.  I would prefer the latter for the last two poins, as this would allow to run jobs at different sites, using local caches.

**Comment by klannon** [comment]
This is the other item we discussed this morning as needing to be addressed before we could release Lobster in the wild.  I think the original list is still valid, but let me try to restate it:

* Picking up the appropriate site stuff (shouldn't be hardcoded to T3_US_NotreDame)
* squid proxy:  We should be able to get this out of the environment (e.g. use the provided squid proxy if one exists.  In fact, it really should be specified in the site local config, but we might have a "chicken and the egg" problem in that we may need the proxy to access cvmfs to get at the site config.  I don't think we want to have the user specifying the proxy at submission either because this won't work with CMS connect, where the jobs can run at many different sites.
* Dashboard reporting should assume Lobster = T3_US_NotreDame.  This one might be hard to deal with because, in the case of CMS Connect, the master probably doesn't know where the workers are running.  But CRAB must also have this problem, so there must be a solution too...

**Comment by matz-e** [comment]
My k$0.02:

* Regarding the proxy, we try to determine that [here](https://github.com/matz-e/lobster/blob/master /lobster/cmssw/data/wrapper.sh#L50) already, using some environment variables or existing site-configs.  Specifying a backup proxy might still be necessary, though.

* For the dashboard, notably there is the [`SyncCE`](https://github.com/matz-e/lobster/blob/master/lobster/cmssw/data/job.py#L423), and the [worker host name](https://github.com/matz-e/lobster/blob/master/lobster/cmssw/data/job.py#L425).  This is on the worker side.

  On the master, we have the [id](https://github.com/matz-e/lobster/blob/master/lobster/cmssw/dash.py#L40), I'm not sure that this is parsed and utilized besides bookkeeping.  Then there is the [tool UI](https://github.com/matz-e/lobster/blob/master/lobster/cmssw/dash.py#L40), which we already set site-agnostic, and the [SE](https://github.com/matz-e/lobster/blob/master/lobster/cmssw/dash.py#L109).

The CE and the SE follow some sort of mapping, I think, i.e., T3_US_NotreDame is associated with ndcms.crc.nd.edu, and I'm not sure that earth is associated with anything?  But I think these are the only two variables we'd need to supply as a user?  Maybe we could get away with just specifying the SE, and inferring the SyncCE from the machine the master runs on?  But then again, I could run a master at home on an SL6 machine, and then we might want to specify the largest CE we run on?

**Comment by klannon** [comment]
I think for CE it has to be the actual CE individual jobs run on, which means the user can't specify it.  CRAB must have a way to determine this because with GlideinWMS, CRAB won't know the CE until the job is matched to the pilot, which must come after the jobs have been created and registered in the dashboard.  (At least, I can't imagine it any other way--but maybe our CRAB3 devs want to weigh in...)  It might be worth peaking at how CRAB registers the CE of a job to see what it does.  Am I making any sense?

**Comment by matz-e** [comment]
The `SyncCE` in CRAB 3 comes from the [job ad](https://github.com/dmwm/CRABServer/blob/master/scripts/CMSRunAnalysis.py#L115).  I'm going to see if I can extract that…

**Comment by klannon** [comment]
I was just looking at this.  This must be something specific from GlideinWMS and not a general condor attribute because I have failed to find it in job ads for our T3.  I suppose we could ad it (or something like it) to the worker submission script.

**Comment by matz-e** [comment]
I think you're right.  This is the relevant output for one of my last crab jobs:

```
job_out.10.0.txt:== JOB AD: Used_Gatekeeper = "osg.rc.ufl.edu osg.rc.ufl.edu:9619"
job_out.10.0.txt:== JOB AD: MATCH_EXP_Used_Gatekeeper = "cluster50.knu.ac.kr:8443/cream-pbs-cms"
job_out.10.0.txt:== Execution site from site-local-config.xml: T2_US_Florida
job_out.1.0.txt:== JOB AD: Used_Gatekeeper = "osg.rc.ufl.edu osg.rc.ufl.edu:9619"
job_out.1.0.txt:== Execution site from site-local-config.xml: T2_US_Florida
job_out.11.0.txt:== JOB AD: Used_Gatekeeper = "grid-arc0.desy.de"
job_out.11.0.txt:== Execution site from site-local-config.xml: T2_DE_DESY
job_out.12.0.txt:== JOB AD: Used_Gatekeeper = "osg.rc.ufl.edu osg.rc.ufl.edu:9619"
job_out.12.0.txt:== JOB AD: MATCH_EXP_Used_Gatekeeper = "cream02.iihe.ac.be:8443/cream-pbs-cms"
job_out.12.0.txt:== Execution site from site-local-config.xml: T2_US_Florida
job_out.2.0.txt:== JOB AD: Used_Gatekeeper = "cmsgrid02.hep.wisc.edu cmsgrid02.hep.wisc.edu:9619"
job_out.2.0.txt:== Execution site from site-local-config.xml: T2_US_Wisconsin
job_out.3.0.txt:== JOB AD: Used_Gatekeeper = "llrcream.in2p3.fr:8443/cream-pbs-cms"
job_out.3.0.txt:== Execution site from site-local-config.xml: T2_FR_GRIF_LLR
job_out.4.0.txt:== JOB AD: Used_Gatekeeper = "cmsgrid02.hep.wisc.edu cmsgrid02.hep.wisc.edu:9619"
job_out.4.0.txt:== Execution site from site-local-config.xml: T2_US_Wisconsin
job_out.5.0.txt:== JOB AD: Used_Gatekeeper = "grid-arc0.desy.de"
job_out.5.0.txt:== Execution site from site-local-config.xml: T2_DE_DESY
job_out.6.0.txt:== JOB AD: Used_Gatekeeper = "osg.rc.ufl.edu osg.rc.ufl.edu:9619"
job_out.6.0.txt:== JOB AD: MATCH_EXP_Used_Gatekeeper = "cmsgrid01.hep.wisc.edu cmsgrid01.hep.wisc.edu:9619"
job_out.6.0.txt:== Execution site from site-local-config.xml: T2_US_Florida
job_out.7.0.txt:== JOB AD: Used_Gatekeeper = "grid36.lal.in2p3.fr:8443/cream-pbs-cms"
job_out.7.0.txt:== Execution site from site-local-config.xml: T2_FR_GRIF_LLR
job_out.8.0.txt:== JOB AD: Used_Gatekeeper = "grid-arc0.desy.de"
job_out.8.0.txt:== Execution site from site-local-config.xml: T2_DE_DESY
job_out.9.0.txt:== JOB AD: Used_Gatekeeper = "grid-arc0.desy.de"
job_out.9.0.txt:== Execution site from site-local-config.xml: T2_DE_DESY
```

There's also the `SyncSite` attribute, which seems easier to obtain (from either the job ad or site config.)

If we start parsing the job ad, which I don't think is present on non-Condor systems, we loose some flexibility.  Apart from that, it sounds a bit like a messy affair.  Maybe we could pass this around in the environment instead/in addition?

**Comment by klannon** [comment]
Let me clarify to make sure we're on the same page with respect to the goals:  The important thing here is that when we run on particular resources, that such resource usage is correctly accounted.  In other words, if we use WLCG resources, we want that accounted for so that CMS has an accurate view of which resources are being used.  If we use ND resources (T3 or opportunistic) we *definitely* want that accounted for so that we can back up claims about how many resources we bring to CMS.  If we use a different source of resources (cluster X) we want to account for that too, or at least not falsely count it under some other resource.

It might not be the most elegant approach, but maybe should take a two part solution:
1.  If the jobs were submitted via a CMS GlideinWMS pool, then we extract the information exactly as CRAB does it.
2.  If the jobs were submitted by hand to a resources (e.g. how we do it at ND, and how we might do it at other places), then we push the site information into the job environment as part of the worker submission.
3.  If the jobs are submitted not via GlideinWMS, and the submitter didn't set the appropriate information as part of the worker submission, then we should list the SyncCE as unknow, but still grab the worker node name.

Does that sound reasonable?

**Comment by matz-e** [comment]
Yes, sounds good.  CRAB's job ad parsing is actually [simple](https://github.com/dmwm/CRABServer/blob/master/scripts/CMSRunAnalysis.py#L76).
