### ISSUE TITLE
Matplotlib encoding issues for some versions of cmssw

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#151]
Matplotlib encoding is messed up for some versions of matplotlib that are shipped in from CMSSW. For example `CMSSW_6_2_0_SLHC12_patch1` does not work, but `CMSSW_5_3_18` does. This really ties into the question that has been coming up more often lately: is it the user's responsibility to track down all of the dependencies (building matplotlib via setuptools is a fantasy, but that didn't stop me from trying-- no dice), or should we switch to building releases for them with the dependencies taken care of?

**Comment by klannon** [comment]
To transfer the knowledge from Slack to here:
* CMS seems to build their own version of matplotlib.
* This issue seems to be with a specific version of the CMS matplotlib: 1.0.1-cms7.  This is used for an SLHC release I'm using, but not 8 TeV analysis (uses 1.0.1-cms8) or apparently the 7x releases (7.4.0 uses 1.2.1-cms3).  (Full disclosure, I haven't tested 1.2.1-cms3 myself.)  Unless this issue rears its ugly head again in a release that has a longer lifespan than CMSSW_6_2_0_SLHC12_patch1, I suggest we just ignore it.  Therefore, I'm just going to close this issue.  (Feel free to reopen it if you disagree with me.)

**Comment by klannon** [comment]
Doh, I'm seeing this now when running Lobster in CMSSW_7_4_7 (1.2.1-cms3).

This is what it looks like, by the way: 
![good-processing-hist](https://cloud.githubusercontent.com/assets/5149849/8860741/cdfca77c-3153-11e5-9f50-35d02b40a740.png)

At this point, I can only guess that I've messed something up in my local installation of lobster and its dependencies?  I installed my local stuff without `cmsenv`'ing because if I did `cmsenv` first, I was getting an error.  I see the directions now say to `cmsenv` in a valid 5_3_X release before installing.  I can do that, but it seems a little wonky.  Should I try it, or do you have a different suggestion.  So far, it looks like I'm the only one experiencing this problem.  (Is that right?)

**Comment by annawoodard** [comment]
## Good catch!! 

The newer CMSSWs are shipping with python 2.7. So to fix your plotting issue, you just need to cmsenv in your release and re-run setup.py in order to set up lobster with the proper dependencies in your `~/.local/lib/python2.7/site-packages`.

**Comment by annawoodard** [comment]
I've just tested that this works. Can you update the documentation?

**Comment by klannon** [comment]
OK, I will try that and let you know if it works.

**Comment by klannon** [comment]
It worked.  To document what I did exactly:
 * Added `setenv PYTHONPATH ~/.local/lib/python2.6/site-packages/:$PYTHONPATH` to get access to setuptools.
  * Re-ran `./setup install --user` in my Lobster directory.

Problems went away:
![good-runtime-hist](https://cloud.githubusercontent.com/assets/5149849/8862267/3105e8e8-315d-11e5-8c4d-f44b3b69698a.png)

Question: `setenv PYTHONPATH ~/.local/lib/python2.6/site-packages/:$PYTHONPATH` isn't in the directions.  It's needed, but just for doing the Lobster installation (at least if you use `./setup.py` directly--I don't know what happens if you install via `pip`.)  Afterwards, you don't need it for running.  I would hate to tell people to permanently add it to their path because maybe they really want python2.7 or a different one in their paths depending on what version of Python they use.  Thoughts?  I guess we need to indoctrinate a new user and have them do the installation from scratch, just to see what the right answer is.  (i.e. do they need this or not using pip...?)

Anyway, I'm closing this issues because installation instructions is really a different issue.
