### ISSUE TITLE
We should differentiate between time lost to eviction and time lost to resource exhaustion.

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#156]
In our plotting, we currently lump time lost to eviction and time lost to resource exhaustion together as 'Lost runtime' in the timeline breakdown (which is true, but not that helpful) and 'eviction' in the pie chart (which is wrong). We should separate them.

**Comment by matz-e** [comment]
Is this still true if jobs with exhausted resources fail?

**Comment by annawoodard** [comment]
Yes (as far as I know, any time a job has exhausted resources, it will fail)-- really I could have included this in the PR for #150, but I remembered it afterwards, so it made sense to just split it into two issues. All we need to do is differentiate between `t_allput - t_goodput` when `exit_code = 16` (exhausted resources) or `exit_code != 16` (eviction is the only other thing that will cause `t_allput != t_goodput` as far as I know, so this completely specifies eviction).

**Comment by annawoodard** [comment]
I've missed a lot while I was away, has the status on this changed @matz-e?

**Comment by matz-e** [comment]
Not really? This has not really been all that high on my list to think about.

That being said, I think this has gotten a bit more complicated since @btovar has a feedback loop to get the resource allocation right. Maybe we should just call it "lost computational time" or something, and not put more effort to puzzle together proper eviction times? We have workers evicted as some measure as to how much eviction is going on…

**Comment by klannon** [comment]
For running I agree.  For "science" I think it's really helpful to be able to distinguish.  This is because as you're developing strategies, what you do for eviction would be different from what you'd do for resource exhaustion (e.g. the latter is almost completely in the user control while the former depends on the dynamic environment).

**Comment by matz-e** [comment]
I think we'd have to rely on @btovar to figure this out… without support from WQ, I'd say it's pretty futile trying to figure out if `allput - goodput` is due to retrying with a bigger resource allocation or due to eviction.

**Comment by matz-e** [comment]
@annawoodard: Isn't this fixed by now?

**Comment by annawoodard** [comment]
Good point. Looks like it was fixed by 6201fb9b.
