### ISSUE TITLE
Rework logging

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#169]
We should ideally not use the logging handler for multiprocessing, as quite a bit of noise creeps into the output.  Instead, we should mimic said logger in a separate class / instance.

**Comment by annawoodard** [comment]
I'm not sure I completely follow. Which noise are you referring to? I'd rather not reinvent the wheel if possible, because more code means more maintenance. The only logging issue I've observed is the fact that logging hangs for some versions of CMSSW. I'd prefer to understand why that happens and if there's a simple fix before we gut logging all together.

**Comment by annawoodard** [comment]
:pensive: I guess so, if we don't have a choice. I'm surprised the multiprocessing module doesn't have better support for this.

**Comment by matz-e** [comment]
I actually think that I started abusing the multiprocessing module for this, and should have just done our own thing.

**Comment by matz-e** [comment]
Adding to this, we should really set up logging in `ui.py`, and then re-route it in `core.py` when desired.
