### ISSUE TITLE
Stage-in via one input method?

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#224]
I'm currently having lots of merge jobs after an ntuplizing run.  I think that instead of testing every single file for input methods we could stop trying to switch methods after a handful of files?  Testing XrootD access for 1-2k files all in the same directory takes quite a while.  Opinions @annawoodard, @klannon?

**Comment by klannon** [comment]
I think this is a good optimization to consider, but we should think 
about all of the impacts.  Right now, the system may lack efficiency, 
but it is very robust.  From one moment to the next, if a particular 
input or output method has problems, it will try multiple fallback 
options.  (Or at least it can assuming the user defines them.)  What 
happens if Lobster decides settle on xrootd and the xrootd server goes 
down.  Will all subsequent jobs fail?  Or can we retain the ability to 
fallback to other mechanisms?  Could we optimize so that Lobster assumes 
a method will be successful, but if it gets a failure, it tries a 
different one?  (Is that kind of the Python way: try-except instead of 
test-try?)  I would also be interested in @annawoodard's perspective.

**Comment by matz-e** [comment]
Sorry, wasn't very clear there.  I'm talking about doing this on the worker for each job.  Currently, a merge job comes in, tests 2k files, and then afterwards tries to read them via XrootD.  Now I was wondering what took the last merge jobs so long and was surprised to find that.  I think that testing the first (few) files only in that case would not hurt, as otherwise, if the XrootD server goes down while we test the rest of the 2k files, the job would fail anyways.

Now this would be on a job-by-job basis, and should not introduce any additional failures.  If something goes wrong, both ways of testing for the input files on the job are screwed.  One by having the first tested files suddenly not being available, the other by the input method going down while reading files.

**Comment by klannon** [comment]
OK, I definitely didn't get that when I first responded.  That's a more 
open-and-shut case.  I have no objections to that optimization.  The 
only thing that I see we'd be giving up is a potentially "creative" mode 
where you distribute your inputs across several different storage 
systems.  You could implement this with a configuration flag to retain 
that ability.  That being said, I'm not really worried about it, so if 
we just want to make the assumption that all inputs are in the same 
place, that's fine with me.

**Comment by annawoodard** [comment]
We wouldn't totally be giving up the mode of distributing your inputs among several different storage systems; as I understand it the testing would stop only after n files tested with the same storage system. So I have no objections, either.

**Comment by klannon** [comment]
@annawoodard:  I'm not sure whether I'm understanding you, but let me give an admittedly contrived example that I think would break with @matz-e's proposal.  Let's suppose that I have access to two different SE's and that for resiliency, I list both as output locations.  During my running SE A drops out randomly once or twice, so when we get to merging, I have some files on SE A and some on SE B.  Let's say that SE A is stable enough that for most merge jobs, even if some of the output is on SE B, the first "N" jobs always come from SE A.  In that case, if I understand correctly, the new behavior would lead to problems because it would test the first N, see they're all resolving to SE A, and then lock in on SE A, later failing when it got to files on SE B.

Would anyone ever do something like this?  Probably not.  So I'm fine with making the change.  If we wanted to be fully inclusive, we'd retain an option to check for every file to allow something like I described above to work if a user really wanted it to.  But I don't think that's really critical and I support the idea of making the merge jobs go faster, so I'm fine with the proposed change even without an option.

**Comment by annawoodard** [comment]
@klannon: Good point! Note though that it would just introduce another inefficiency, not be a totally lost cause, as long as we're properly dealing with skipped files (which I believe we are doing, at least for EDM files, but I haven't looked at that part of the code in a while.) In your example, the failed SE B files would eventually be collected together into one all-SE-B merge job.

**Comment by matz-e** [comment]
@annawoodard that would be the case if we let merge jobs skip files (#69), which I think we should resolve at least for EDM output.

**Comment by klannon** [comment]
I'm am opposed to any change that makes EDM and non-EDM merge jobs act significantly differently, unless there is a really good reason to do this.  I would rather see neither type skip files than only one.

**Comment by matz-e** [comment]
Maybe #69 can wait then.  I'll want this in sooner than later, as it makes it hard to tell if a task is stuck or just taking forever querying xrootd for files to merge.  It'll be tunable and most likely should just be used in the `output` setting;  if the `input` SE is used to access several hundreds/thousands of files in one task, I think something else is wrong.

**Comment by annawoodard** [comment]
Sounds good to me.
