### ISSUE TITLE
Randomize seeds for MC production

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#250]
@annawoodard, @klannon: this should probably be optional, or the user should be able to set this? I did a trial MC generation run and found the same seeds everywhere.

The idea here would be that we should be able to take a config out of MCM and use it in Lobster unmodified, where Lobster just does the right thing w.r.t. events / lumi, seeds for the random number generator.

**Comment by klannon** [comment]
We don't want the same seeds everywhere!  I seem to remember that I did a run once where I didn't take any care to set the random seeds and ended up generated 20 times the same events instead of 20 times the total statistics!  We want to avoid that, I think.

I don't know how much is already done in McM or what research you've done, but a few months back, I looked into random seeds and below is what I came up with.  Use it if it helps you:

======
Basic info on Random number generation:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideEDMRandomNumberGeneratorService#Before_the_Service_Sees_the_Conf

Basically, the above says that the initialization of random seeds is left to the workflow tool and if you do nothing, you get just the default random seed for every event.

There's also a lot of stuff that I don't understand about lumiblocks and event offsets.

This page talks about doing good Python things with random number seeds:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuidePythonTips?redirectedfrom=CMS.SWGuidePythonTips#Reset_the_random_seeds_every_tim

It basically gives a snippet that tells the random number service to pick a unique random number every time.  They point out this destroys reproducibility.

**Comment by matz-e** [comment]
Reading your links.  Forgot to add that this is akin to what production seems to do for random seeds:
```
from IOMC.RandomEngine.RandomServiceHelper import RandomNumberServiceHelper
helper = RandomNumberServiceHelper(process.RandomNumberGeneratorService)
helper.populate()
```

**Comment by matz-e** [comment]
And that's also in one of your links.

**Comment by matz-e** [comment]
Question is, should I add that to be the default when not running over any input files? We can always add an option to turn it off. With more work, we can also get reproducible seeds, but I think I'd like to have chained workflows first.

**Comment by klannon** [comment]
Do it.  I'd rather have something that works quickly than wait a long 
time to work out a "better" solution.  It's hard for me to imagine a 
scenario in which we'd care about reproducibility.
