### ISSUE TITLE
Need Way to Cap Number of Running Jobs For Specific Workflows

### ISSUE THREAD

**Issue by klannon** [matz-e/lobster#275]
Digi completely saturates the campus bandwidth, but Lobster chooses to run only that because of the distribution of jobs.  Need a way to tell it don't run more than XX jobs of this type so it will continue to make progress on other steps as it can.  (There's still plenty of GS to do, but it choose digi because that's the step with the most available work to do, I think...)

**Comment by matz-e** [comment]
Aren't you just shifting the problem around, then? The RECO/mAOD tasks will catch up with the DIGI step, while the GS will finish, and in the end, not all cores will be used due to the cap on the DIGI step.

From a technical view, implementing this would require to keep track of the running tasks per workflow (or category in WQ, would there be any incentive to add per-category stats to WQ, @btovar?), which we could do via the status function implemented for the dashboard reporting. There'd be some cross-referencing, probably not very elegant/clean, but it can be done. This would then affect how many tasks we should but in the queue… (running + queued tasks ≤ threshold)

Now if it's implemented, how are we going to estimate the number of tasks needed to saturate bandwidth? This may depend on the processing speed (CPU speed/local resources), as well as dataset/configuration chosen. Maybe it would be better to have this in WQ? There could be a global/category resource of bandwidth that the resource-monitor could measure and adjust the tasks to? Then we could have WQ automatically adjust the number of running jobs from that workflow. We would also have to provide some way of adjusting this limit while Lobster is running, via IPC, otherwise there would be a lot of user-side fine-tuning, I think.

**Comment by btovar** [comment]
Adding stats per category does seem like a nice thing to have.

**Comment by klannon** [comment]
@matz-e:  All good points.  To answer your main question, I still think this would be useful because it would let me use the maximum possible bandwidth while leaving the other slots free.  For example, let's say that running more than 500 digi tasks saturates the bandwidth.  In the current setup, the only way I can control this is to moment by moment estimate what fraction of the running tasks are digi (call this "f") and then set my maximum number of workers in WQ such that I can run at most 500/f tasks.  As "f" changes, I have to keep trying to change the WQ maximum so that it stays within bounds.  And, since "f" is essentially chosen by Lobster on the basis of how much work is left to do for each workflow, at some point, "f" could reach 1.0, in which case, I can only use 500 cores, even if there are 5000 available and I could just go ahead and finish the LHE and GS stages.  Maybe in a steady-state world, the overall time wouldn't really change, assuming Lobster is optimally picking what to work on so that the tasks finish as fast as they can, but in the real world of opportunistic computing, this might mean that today, when I have 17k cores, I can't use them to run extra GS jobs, and tomorrow, when I'm down to just 1k available cores, I'll be sorry that I didn't get a head start on the GS.  Make sense?

Maybe this is more of a long term project, but in the end, I think it would be really helpful to be able to define caps in Lobster/WQ such that we're never running more than XX tasks of a given type.  It doesn't matter so much to me where this cap is defined, as long as its fine grained enough that I can cap digi jobs without capping other workflows.

Regarding how a user would know what the cap should be, they probably wouldn't until after the job was already running.  So however it's implemented, we should do it in such a way that it can be updated during the run without interrupting existing processing (e.g. the way you can adjust work_queue_factory parameters on the fly by editing the config file).

Ultimately, it would be great to have hooks such that you could define things like overall bandwidth for a given site and Lobster/WQ/etc. would run the maximum number of jobs that the site could support.  That will be hard and definitely long term.  First putting user knobs in the right place so that a user could do this manually (e.g. based on getting an angry phone call from OIT) I think would be a great start towards this ultimate vision.

**Comment by matz-e** [comment]
OK, I'd then like to get some other changes in before pinning this down. Mainly verifying the configuration, allowing the configuration to be altered with Lobster running. By then, maybe we can get stats on a per-category basis out of WQ, too, which will simplify capping the number of tasks a lot.

**Comment by klannon** [comment]
This sounds like a good plan to me.  So, just for completeness, you're saying
 1.  #13
 2.  #28 
 3.  Then @btovar's change to WQ for per category stats.  (@btovar, do you want a github issue to make the request formal?)
 4.  Then implement the ability to cap number of running jobs per workflow.

Does that sound about right?

**Comment by btovar** [comment]
Yes, thanks!

**Comment by matz-e** [comment]
Add #276 to the list.
