### ISSUE TITLE
Syncronize configuration with stored one

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#28]
We should offer the possibility to update settings based on an updated config passed to lobster.  This includes cross-checking which settings can be altered without any double-checking, which need confirmation by the user, and which should not be changed.

**Comment by klannon** [comment]
Are you thinking something like a `lobster update config.yaml` command, which would give Lobster a chance to validate the new config along the lines of #13 and what you stated above.  If the config is good and the user hasn't tried to change any illegal parameters, then `lobster update` can just replace the old config in the working directory with the updated one.  Otherwise, it can give the user a helpful (or at least explicit) message saying the config has a problem and it won't be updated.

Presumably, Lobster doesn't currently re-read its config periodically.  If we implement this, we'd probably also want to have Lobster occasionally re-read its config, right?

**Comment by matz-e** [comment]
I'm actually thinking about something more complex. I have a branch open which turns the whole config into a python object, which allows for config verification (would be a real pain with YAML), and has a more fine-grained split of settings.

Then I think instead of re-reading the config, we should update settings directly via IPC. Comparing two configs is another issue that seems quite complicated to get right, and then propagating the changes to the right python variable is needed. If everything is in one python object tree, modifications will be available immediately.

**Comment by klannon** [comment]
OK, well it seems that you're deeper into this than I can hope to be in the near future.  My only request is that changing a running lobster config should require some explicit action by the user (e.g. it shouldn't be an implicit side-effect of editing a config) and if the change won't be propagated to the master, the user should get unambiguous feedback to that effect.  Nothing is more frustrating when debugging than thinking you've made some change that never actually propagated because of some silly mistake.

**Comment by matz-e** [comment]
Yes, it'll be explicit. And I understand that there should be feedback about any value change. They should actually be logged and reported back to the user on the command line.

**Comment by matz-e** [comment]
I've implemented it such that feedback is provided in the main Lobster log. Two-way communication via unix utilities without the need of a full blown internet socket is not quite feasible.  Sample change command:
```
(.lobster)earth: ./lobster.py reconfigure workdir 23456 examples/test2.yaml
2016-01-20 07:05:11 [INFO] lobster.reconfigure: sending command: config.workdir = 23456
2016-01-20 07:05:11 [INFO] lobster.reconfigure: check the log of the main process for success
```
And Lobster processing log:
```
2016-01-20 07:05:28 [DEBUG] lobster.actions: received commands: config.workdir = 23456
2016-01-20 07:05:28 [ERROR] lobster.actions: caught exeption from command: can't change attribute workdir of type <class 'lobster.core.config.Config'>
```
This will allow to change only certain whitelisted values, as we will have to take care that the changes are being propagated (I haven't done this yet).

**Comment by matz-e** [comment]
(Oh, and this is on the `python-config` branch, which will make you shuffle some settings around. As a bonus, you will not be able to have typos in your config anymore)
