### ISSUE TITLE
Should be able to specify a minimum number of queued tasks per category

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#283]
See title… @klannon is concerned about using every last bit of every worker, so we should be able to always keep a number of "lesser" multi-core tasks queued to shim into unfilled workers.

**Comment by annawoodard** [comment]
I think we should try to set a sensible default here so that things work as well as possible out-of-the-box, and users should only have to set this by hand for special cases. Maybe this should be a minimum _fraction_ of queued tasks rather than minimum number, and that fraction should have a sensible default. I think that we should try to keep the categories processed as evenly as possible.
