### ISSUE TITLE
Need a way to dump configuration

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#286]
The current feature set includes ways to change configuration settings, but we need a way to query them, too.

**Comment by annawoodard** [comment]
What is the most common scenario here? I see it as: 

1. You don't know what settings to use so you try a run with guesses
2. See that disk, memory, or runtime needs to be adjusted
3. Adjust it
4. Manually change your config to reflect that, so that you don't need to guess and adjust next time you run it

So I think it makes the most sense to do (4) automatically, by updating the configuration file in the working directory. Once we implement that, an additional method of querying the configuration might be redundant. (Note: I might be totally missing the point here, because I've been out of the loop a while. Sorry if so.)

**Comment by matz-e** [comment]
The updated configuration is already stored in the working directory… pickled. Also, there may not be a current configuration corresponding to the working directory anymore. I had in mind something like reproducing the original python configuration from the python object, kind of like CMSSW does it. Just with updated values. That would also make #273 pretty easy…

**Comment by annawoodard** [comment]
> So I think it makes the most sense to do (4) automatically, by writing the updated configuration file to the working directory.

I meant writing the updated python configuration here-- I know we write a pickled config, but you can't modify and re-run a configuration with the pickled file :smile:. What I usually do is start with my last working configuration and change the label, etc if I'm running a similar workflow. So it makes sense to write the updated python configuration itself in addition to the pickled one, so that the adjustments the user made are preserved in a human readable format, since that's where they'll start for their next configuration. Sorry I wasn't clearer. What I meant was that we should automatically reproduce the original python configuration in the working directory. So I think we're almost in agreement, let me try to summarize to see: I think whenever the user updates the configuration, we should write out the updated python configuration to the working directory, and that that probably makes a separate dumping utility unnecessary because it eliminates the need for the user to remember to call the dumping utility each time; you think we should implement a command line dumping utility to write out the configuration on request. 

What do you mean, that there might not be a current configuration corresponding to the working directory anymore?

**Comment by annawoodard** [comment]
One more thought in support of my position: we used to write the python configuration to the working directory but stopped doing that-- I think that's a mistake, from a 'data preservation' standpoint. We should take every opportunity to make it easier for the user to reproduce their work. We should assume that they will make mistakes if they are permitted to do so-- for example, by losing their original config, or modifying it after running it so that it no longer really corresponds to the work they think it does. One extra way we can protect them from themselves is by maintaining a copy of the most up-to-date python config in the working directory.

**Comment by klannon** [comment]
I think you are both right and the solution is to have some code to unpickle the default config and turn it back into human-readable python config.  Once we have that, I would be in favor of having Lobster run that to produce the updated python basically every time it updates the pickled file.  The only drawback I can see is that we also have to decide what to allow for the user who thinks that updating the config in the working directory (or the original one in the home directory) would change Lobster's behavior.  My understanding is that it doesn't anymore because Lobster relies on the pickled config.  We also don't want people to think they can update arbitrary elements in their config because that will never be true.  Thoughts?  Put a big printout in the config in the working directory saying modifying this config will have no impact on the running/restarted project?

**Comment by matz-e** [comment]
BTW, technically, you could unpickle the pickled config, change values, repickle and pull some CRAB2 trick to re-use it.

OK, Kevin was faster than me. I agree with what's being said. Another thing about Lobster not reading in the dumped config again: maybe we would like to not have the user to poke around the working directory? I.e. regarding it as a closed blackbox.  In that case, I'd favor just providing a command to reproduce the config from what is pickled?

**Comment by klannon** [comment]
I'm fine with that idea.  I'm definitely in favor of making it so that the average user isn't encouraged to tinker with their working area.

**Comment by annawoodard** [comment]
> BTW, technically, you could unpickle the pickled config, change values, repickle and pull some CRAB2 trick to re-use it.

Noooooooo, we are an evolution, no CRAB2 tricks should be required!

But yes, I'm fine with the idea of offering a tool to reproduce the config from what is pickled. Making it harder to change anything in the working directory is definitely in line with 'protecting the user from themselves'. :smile: The key here is that since it will take the pickle file, we don't rely on them to remember to call it before moving on to the next project.
