### ISSUE TITLE
Document required numpy version

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#294]
```
==> /tmpscratch/users/awoodard/lhe_23d_v18a/process.err <==
  File "/afs/crc.nd.edu/user/a/awoodard/lobster/lobster/actions.py", line 44, in plotf
    plotter.make_plots(foremen=config.foremen_logs)
  File "/afs/crc.nd.edu/user/a/awoodard/lobster/lobster/commands/plot.py", line 963, in make_plots
    bad_hosts=self.find_failure_hosts(failed_tasks),
  File "/afs/crc.nd.edu/user/a/awoodard/lobster/lobster/commands/plot.py", line 593, in find_failure_hosts
    hosts, counts = np.unique(failed_tasks['host'], return_counts=True)
TypeError: unique() got an unexpected keyword argument 'return_counts'
```
CMSSW_7_4_15 sets up numpy 1.6 for me, It looks like the 'return_counts' keyword was introduced in numpy 1.9.

I see that I can access numpy 1.9 at ND here `/afs/crc.nd.edu/x86_64_linux/python/2.7.8/lib/python2.7/site-packages/numpy` by loading the module but, with non-ND collaborators coming on board, I think we should try to document a more general way of accessing the required version. I agree with previous conversations that it is beyond our scope right now to completely decouple from CMSSW... Are there CMSSW releases that are setting up numpy 1.9? If so, we can just recommend them in the docs. Where are you pulling numpy from, @matze?

**Comment by klannon** [comment]
I don't know about @matz-e, but I was getting it from CMSSW_7_6_1 because I was running MC jobs that use that release.  That release ships with numpy 1.9.2.  I'm guessing Matthias was doing something similar.  Run 2 data analysis is based on 76x and moving to 8xx starting later this year.

I completely agree that it would be optimal to document the versions of all Python packages Lobster uses, especially for the far off future when we decide to run without CMSSW.  Is there an easy way to do this (i.e. a tool to extract all the Python dependences and which version is being used)?

In the short term, I guess the best option would be to update the docs to say we assume you're using CMSSW_7_6_x instead of 7_4_x.  How do you update the fancy new documentation website?

**Comment by matz-e** [comment]
There is some dependency handling possible in `setup.py`, and I think it's even possible to install the required numpy version via pip…

@klannon (and potentially @annawoodard, although I have the suspicion that you may already have found this): the new documentation currently lives [here](https://github.com/matz-e/lobster/tree/master/doc/source), although I think we should move that to `docs`, like most other projects do.

**Comment by matze** [comment]
@annawoodard: please stop notifying me. That's the third issue this week I receive notifications because you wrongly address me instead of @matz-e.
