### ISSUE TITLE
Add newline at the end of report.json

### ISSUE THREAD

**Issue by yannakopoulos** [matz-e/lobster#374]
Logstash uses newlines to delimit log events, so if an event doesn't end with a newline, Logstash assumes it's not done being written and won't read it. `report.json` ends on a curly bracket instead of a newline, meaning that the final curly brace will never be read and the JSON won't be parsed correctly. This precludes real-time indexing of these files in Elasticsearch.

**Comment by khurtado** [comment]
Are you planning to use the `json filter` or to decode using the [json codec plugin] (https://www.elastic.co/guide/en/logstash/current/plugins-codecs-json.html)? I'm asking because the latter seems not to require `\n` (there is a `json_lines codec` also which does expect you to end with a newline though). 

I'm not a Logstash expert here, so I'm just asking :)

**Comment by yannakopoulos** [comment]
The problem isn't the codec or the filter, it's Logstash itself. Logstash actually won't ever read the last curly bracket without a newline after it, because it thinks there might be more yet to come on that line, so that last curly bracket won't ever be passed to any filter or codec to parse.

**Comment by khurtado** [comment]
Got it, thanks!

**Comment by matz-e** [comment]
I'll try to get my physics stuff together, add some more logging and add the above branch in a test run today.

**Comment by matz-e** [comment]
This file seems to have the right format?

    /tmpscratch/users/matze/ttH/v28/ttH2TT_125_ext1/failed/0000/0031/report.json

**Comment by yannakopoulos** [comment]
Yep, that one works.
