### ISSUE TITLE
Optimize default task creation algorithm.

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#391]
When creating tasks, we currently ([here](https://github.com/matz-e/lobster/blob/master/lobster/core/config.py#L94) and [here](https://github.com/matz-e/lobster/blob/master/lobster/core/source.py#L365)) cycle through the categories so that the smallest task limit is processed first. If no task limit is specified, the default sort is on the category name. I think we should consider alternate default sorting methods. For example, we could sort by number of units available such that we keep the categories processed as evenly possible. This has two advantages: 1) it is likely that different categories have different bottlenecks, so maximizing the mixing might minimize the per-category bottlenecks, and 2) for chained workflows with different categories at various steps, this would mean that halfway through processing you'd have half of your last step processed, which might be useful if you want to start using output before the entire project is finished.

See, for example, my current situation, where I'm only running digi and reco tasks at a severe inefficiency because I have 513 fit workers but only 251 tasks running, but there are plenty of mAOD tasks that could be run.

This could also be partially addressed by changes on the factory side which I believe @btovar is considering, although I think the points above would still stand.

```
(.lobster) [earth] ~/lobster-spring-16-scale-test/ttW >work_queue_status -A earth.crc.nd.edu 9001
CATEGORY        RUNNING    WAITING  FIT-WORKERS  MAX-CORES MAX-MEMORY   MAX-DISK
digi                247       1002            0         ~4      ~4400     ~22131
reco                  4          0          513         ~5      ~4400      ~4504
```

**Comment by matz-e** [comment]
The creation process should create tasks proportionally to the work available, **regardless** of the order of the workflows/categories in the creation process. If there's more work available for `digi` than for `reco`, more `digi` tasks should be created. IIRC this should factor in tasks waiting, i.e., if `reco` tasks are all running, more should be created as soon as cores are marked as available by Lobster. I'll dig out some stuff later…

**Comment by annawoodard** [comment]
Good point about the order not mattering. Sorry, I'm traveling and can't remind myself what's in the code very carefully. But I think the above comment still stands- it would be preferable if we created tasks, trying to keep the categories processed as evenly as possible. In that case I would be running mAOD and could use more workers without changing the factory settings. This is all just a brainstorm I might be missing something obvious here. I guess it's not obvious what results in optimal packing and maybe the only way to do this best is on the factory side with a factory that can submit workers to match the tasks as @btovar is considering.

**Comment by klannon** [comment]
We had discussed in the past that Lobster should keep a minimum number 
of *waiting* tasks in the queue so that if there were any sort of fit 
issues, tasks that Lobster might not choose to run but that would at 
least fit, would get put in.  I can't remember if this was actually 
implemented or not.  Of course, this relies on WQ going through all the 
tasks and making sure to try all of them for a fit, not just giving up 
part of the way through the list.  (I don't know if this has a name, but 
I think this should be called the Cinderella problem because if you 
don't check all the way to the end looking for a fit, you'll be sorry.)  
@btovar, can you comment on how this would work from the WQ side.

So, what I'm imagining is that regardless of the algorithm based on work 
remaining, Lobster would always decide to submit at least, say, 10 new 
tasks unless there were at least that many tasks in the waiting/idle 
state (or it didn't have any more tasks from that category to submit).  
That way, if digi tasks are blocked because of resource fitting issues, 
mAOD could get through still.

Regarding the evening issue, is it possible that things get out of whack 
because of the total number of tasks.  I don't know the actual numbers, 
but imagine that step A has 200k tasks and step B has 2k (because every 
task from step B runs over the output from 100 step A tasks.  Then, even 
if step B is 90% done (i.e. 20k tasks remaining), would Lobster still 
submit mostly step A tasks because there are only 2k step B tasks to run 
but still 20k remaining for step A?  In other words, if you want things 
to progress through the same fraction of the work, then the algorithm 
that decides how many tasks to submit should be based on fractions not 
number of units.  (I'm not sure which it is right now.)

**Comment by btovar** [comment]
If there is at least one worker with some space to run a tasks (e.g., at least 1 core, 1 MB of memory, and 1 MB of disk), then wq will try to fit tasks to it. Only when all the workers are completely busy, waiting tasks are not considered.

**Comment by annawoodard** [comment]
> We had discussed in the past that Lobster should keep a minimum number
of *waiting* tasks in the queue so that if there were any sort of fit
issues, tasks that Lobster might not choose to run but that would at
least fit, would get put in.  I can't remember if this was actually
implemented or not. 

To be clear, we have `category.tasks` to specify minimum queued tasks, but I'm saying if we can determine the optimal behavior we should do that by default. I can't check the code right now but I think @klannon is right about fractions vs total number.

**Comment by matz-e** [comment]
@annawoodard that's the maximum number of tasks, /me thinks. The minimum is covered by #283 and not yet implemented. I'll see to that plus a simplification of the creation code.

**Comment by annawoodard** [comment]
Ugh, I'm sorry, everyone. I should just not try to participate by quoting things from memory while I'm AFK without checking anything. I'm just making noise. 

I still think that further than just simplification, we need to do things by fractions as @klannon mentioned above if we're not doing that yet.

**Comment by matz-e** [comment]
How you define the fraction though is the question, I think by now. IIRC, the current definition is `number of cores occupied tasks created for 1 category = available cores / (available remaining units for category / available remaining units total)`. I guess the code could need some refactoring to simplify all this.

**Comment by matz-e** [comment]
Forgot… actually, it is:
```
number of cores occupied tasks created for 1 category = available cores / (available remaining units for category / available remaining units total) - tasks queued for category
```
And then there's some number adjustment for categories with maximum number of tasks…

**Comment by matz-e** [comment]
I've quickly factored out the algorithm and re-written it simpler, and, IMHO, more legible. @klannon, @annawoodard do you want to have a look over it [here](https://github.com/matz-e/lobster/pull/394/files#diff-4a573b6e296dd3ca957041da8e3565fdR25)? Everything should be weighed by `remaining_tasks * ncores`, and tasks allotted proportionally to that (the number of queued tasks should reflect the proportion), with adjustments for minimum and maximum of allowed tasks.
