### ISSUE TITLE
XrootD proxy/cache server stress tests

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#480]
@matz-e @WenzhaoLi @klannon @khurtado 

Let's collect the progress here on the server stress tests.

test | plan | status | results | notes |
 ------------ | ------------ | ------------- | ------------ | ------------ | 
0 | run `simple.py`before wiping caches to test config, optimize factory settings, cache DAS queries | DONE | |
1 | saturate all servers at once with `simple.py` | | inconclusive | Unable to push the network very hard; it seems to be a combination of fast tasks causing too much load on the Lobster master and not reading many collections in the input files.
2 | saturate servers all at once with `TauRoast` | | Pushed ~17 Gb/s with 1.5k tasks | No significant performance boost from the new servers.

**Comment by klannon** [comment]
As mentioned on Slack, for this we need a list of datasets.  @matz-e can you start with the data + MC list for your analysis and then I can ask @muell149 if he can give us his as well?

**Comment by annawoodard** [comment]
See [here](https://github.com/cms-ttH/ttH-TauRoast/blob/master/python/datasets.py) for @matz-e 's.

**Comment by annawoodard** [comment]
@khurtado Can you let us know when the caches are wiped and it's ok to proceed?

**Comment by klannon** [comment]
Wait, shouldn't we have @WenzhaoLi prep the config and test that it runs first, and then wipe the caches?

**Comment by annawoodard** [comment]
Good point!

**Comment by klannon** [comment]
To accelerate the process for @WenzhaoLi could one of you take @matz-e's file above and merge it with `simple.py` to give a starting point.  I'll ask @muell149 for his dataset list and then @WenzhaoLi can take care of adding whatever isn't already on @matz-e's and verifying that he can run some jobs with a small number of workers (maybe 100).  We can use the small run to check two things: (1) bandwidth per worker so we know how many workers we need to try to max out the cache servers and (2) proper worker/job sizing requirements so that we use the resources efficiently.  Then we can ask @khurtado to wipe the caches and start the test over with a large number of workers.

**Comment by annawoodard** [comment]
OK, I'm on it.

**Comment by WenzhaoLi** [comment]
Sorry I was AFK. What did I miss..

**Comment by klannon** [comment]
Basically, you got nominated to take the lead on some important tests because you know how to use Lobster and you haven't used up all your priority in HTCondor!  If you can stop by my office before 2pm today, I can explain it to you in person.  That would probably be easier than trying to type it all here.

**Comment by annawoodard** [comment]
I pushed something to get you started @WenzhaoLi [here](https://github.com/matz-e/lobster/tree/fall-2016-cache-proxy-stress-test).

**Comment by annawoodard** [comment]
Note @WenzhaoLi I just disabled merging in the testing branch. If we want to light these servers up, let's not mess around :smile:.

**Comment by annawoodard** [comment]
Also disabled output file return as suggested by @matz-e.

**Comment by WenzhaoLi** [comment]
@annawoodard Okay, thanks! I guess I can start the run now?

**Comment by klannon** [comment]
FYI:  We might not need it if we use @matz-e's mega list of datasets, but here's the list of datasets @muell149 uses: https://github.com/cms-ttH/ttH-13TeVMultiLeptons/blob/master/TemplateMakers/test/multicrab3.py

**Comment by annawoodard** [comment]
Good to know! I propose we start with these for the pre-test test prior to wiping the caches and see how things go-- we'll add more if needed.

**Comment by annawoodard** [comment]
> @annawoodard Okay, thanks! I guess I can start the run now?

@WenzhaoLi You are cleared for lift-off.

**Comment by klannon** [comment]
Definitely.  My main concern is that when we do the big test, I'd like to have effectively an infinite list so that (a) we don't run out of work before we finish ramping up.  It can take ~hours to ~days to claim your resources in our current HTCondor configuration and (b) we maximize the number of different sites we hit because honestly, I'm worried that our biggest obstacle in getting to 50 Gb/s will be finding enough sites to give us 3-4 Gb/s each to reach our goal.  (50 Gb/s = all cache servers completely saturated...)  Lobster still randomly shuffles tasks to keep us from hitting a patch were all the inputs are located at one (crappy--Florida, I'm looking at you...) site, right?

**Comment by annawoodard** [comment]
Summarizing from Slack: we cycle through the datasets to create new tasks, weighing by the number of lumisections in the dataset, in order to keep roughly the same proportion of each dataset processed.

>  I'd like to have effectively an infinite list 

I'll update the dataset list to be the union of @matz-e and @muell149.

**Comment by annawoodard** [comment]
Dataset lists are updated and @matz-e fixed the output file disabling.

**Comment by annawoodard** [comment]
The new servers are ordered, so I'm closing this issue. It has been decided to stay with the old (cheaper) configuration because we didn't notice a significant performance boost from the more expensive machines.
