### ISSUE TITLE
Files not cleaned up after merging

### ISSUE THREAD

**Issue by klannon** [matz-e/lobster#558]
Reported by @muell149 on 02/22/2017.  Symptom is that some files that have been merged are not cleaned up.  Not sure why?  The log file shows the call to remove the files after merging.  Snakebite problem?

**Comment by annawoodard** [comment]
see `/tmpscratch/users/cmuelle2/lobster_test_feb17_Moriond17_v0/`

**Comment by matz-e** [comment]
Yes, may be the case, I've observed that, too. This warrants more investigation. Funny enough, the validation code should use the same mechanism as the cleanup while running…

**Comment by annawoodard** [comment]
The reason so many files are not getting deleted is because if one file doesn't exist, the whole `snakebite` call fails:
```python
    def remove(self, *paths):
        try:
            for data in self.__c.delete(list(paths)):
                pass
        except snakebite.errors.FileNotFoundException:
            pass
```

I think that the reason this doesn't cause problems when running `validate` is that it looks through, workflow by workflow, and for each calls `ls` and [creates](https://github.com/matz-e/lobster/blob/master/lobster/commands/validate.py#L47) a set of the files it knows exist. Then it finds the intersection of that set and the files it knows shouldn't be there. So when it calls `remove`, it's only on files that `ls` already told us are there.

In `source.py` on the other hand, we always try to remove the output of failed tasks. While that's prudent to do, it's not surprising that often those files are missing.

I looked through the `snakebite` source, but I didn't see any easy solutions (like a delete-everything-possible-and-do-not-complain-about-files-not-found option).

I looked at the hit we take from going one-at-a-time, and it is significant (it takes about twice as long.) I also tried to somewhat-replicate what we do with validate, but that took three times as long (this is a worst-case scenario, it might be better realistically with fewer workflows):

```python
import os
import snakebite.client
import snakebite.errors
import time

client = snakebite.client.Client('eddie.crc.nd.edu', 19000)
base = '/store/user/awoodard/lobster/test'
num_files = 1000

def make_test_files(paths):
    list(client.mkdir([os.path.dirname(p) for p in paths]))
    list(client.touchz(paths[:-1]))

paths = [os.path.join(base, '{0}/{0}.txt'.format(i)) for i in range(0, num_files)]

start = time.time()
make_test_files(paths)
for path in list(paths):
    try:
        client.delete([path]).next()
    except snakebite.errors.FileNotFoundException:
        pass
elapsed = time.time() - start
print 'one at a time for {} files took {:.0f}s'.format(num_files, elapsed)

start = time.time()
make_test_files(paths)
try:
    for data in client.delete(paths):
        pass
except snakebite.errors.FileNotFoundException:
    pass
elapsed = time.time() - start
print 'all at once for {} files took {:.0f}s'.format(num_files, elapsed)

start = time.time()
make_test_files(paths)
dirs = [os.path.dirname(p) for p in paths]
safe_paths = set(paths) & set([data['path'] for data in client.ls(dirs)])
try:
    for data in client.delete(safe_paths):
        pass
except snakebite.errors.FileNotFoundException:
    pass
elapsed = time.time() - start
print 'checking first, then all at once for {} files took {:.0f}s'.format(num_files, elapsed)
```

gave this:
```
one at a time for 1000 files took 82s
all at once for 1000 files took 41s
checking first, then all at once for 1000 files took 123s
```

The first option is slow but reliable, while the second is fast but unreliable. I propose that as a compromise, we raise the exception in `lobster.se.Hadoop.remove` so that if the call fails, it will be tried again with the next protocol. Then in `source.py` we call `fs.remove` twice instead of once: first for the outputs of failed tasks (which are likely to be missing), and then again for the merge files and input cleanup files (which are likely to be where we expect them.) In this way we may see a slowdown, but it will be mitigated because we'll be using the slower protocols on fewer files.

**Comment by annawoodard** [comment]
Rather than raising the exception and moving to the next protocol, we could just try one-at-a-time in the `except` clause if there's a `FileNotFoundException`. Even one-at-a-time, `snakebite` is still probably our best bet. Coupled with splitting up the `remove` calls into more-likely-to-fail and less-likely-to-fail, we'll probably be in better shape.

**Comment by annawoodard** [comment]
Another option, assuming [WAL](http://www.sqlite.org/wal.html) mode in sqlite works as expected and we don't lock the DB as long as we're just reading, would be to take the file cleanup duties out of the master completely and just run validate periodically.

**Comment by matz-e** [comment]
> The first option is slow but reliable, while the second is fast but unreliable. I propose that as a compromise, we raise the exception in lobster.se.Hadoop.remove so that if the call fails, it will be tried again with the next protocol. Then in source.py we call fs.remove twice instead of once: first for the outputs of failed tasks (which are likely to be missing), and then again for the merge files and input cleanup files (which are likely to be where we expect them.) In this way we may see a slowdown, but it will be mitigated because we'll be using the slower protocols on fewer files.

This and your other comment:

> Rather than raising the exception and moving to the next protocol, we could just try one-at-a-time in the except clause if there's a FileNotFoundException. Even one-at-a-time, snakebite is still probably our best bet. Coupled with splitting up the remove calls into more-likely-to-fail and less-likely-to-fail, we'll probably be in better shape.

Excellent! Let's do that!

**Comment by matz-e** [comment]
> Another option, assuming WAL mode in sqlite works as expected and we don't lock the DB as long as we're just reading, would be to take the file cleanup duties out of the master completely and just automatically run validate periodically in a separate process.

I had thought about that before. It would be another process to keep at bay, and that has proven to be complex with the plotting. If we can get it to work with your other suggestion, I think that would be preferable in terms of complexity. Another argument for it:

* Only when we delete merged files we're going to deal with thousands of files to be removed. With failed tasks, if we get thousands, we have bigger fish to fry than to worry about the efficiency about file deletion.

**Comment by annawoodard** [comment]
> Only when we delete merged files we're going to deal with thousands of files to be removed. 

Great point!

> With failed tasks, if we get thousands, we have bigger fish to fry than to worry about the efficiency about file deletion.

Agreed!
