### ISSUE TITLE
Lobster in pypi

### ISSUE THREAD

**Issue by matz-e** [matz-e/lobster#575]
Thoughts @klannon, @annawoodard?

We could cut regular releases (the one using 142 before the whole dashboard shenanigans would have been a good candidate), and declare them super-stable…

**Comment by annawoodard** [comment]
:+1: from me

**Comment by klannon** [comment]
I have no objections to pypi, but I also can't strongly endorse it because I just don't know well enough how it works.  I'm not sure that we've had much luck with the concept of releases in any prior incarnations of code management.  It seems like we never know when to cut a release until we're missing it!  Anyway, at this point, I'd suggest doing whatever is simplest for long-term sustainability, keeping in mind that you two won't be maintaining this forever (or I guess, possibly even 6 mo. from now...)

**Comment by annawoodard** [comment]
Just to clarify: my :+1: was in support of Lobster in pypi. I don't have anything against releases, but I agree with @klannon that we haven't had much luck curating them in the past. As a small and research-oriented project, the "use the latest master unless it's broken, in which case fix it or roll back until it's not broken" approach hasn't been working out _that_ badly. So we should try to do releases but plan for not keeping up with them well, or them not being very useful because they're missing this or that.

This doesn't preclude cutting regular releases, but what sounds more exciting to me would be using Travis as @PerilousApricot mentioned to automatically upload to pypi. Why not do so on all new commits to master? Let's double down on CI.

**Comment by matz-e** [comment]
It's not a priority I would say, but would be nice to have in the end. We should actually be tagging versions that work more often, and keep some sort of changelog around. Especially before we do major changes like what @WenzhaoLi is currently doing.

**Comment by PerilousApricot** [comment]
For my 2c, popping lobster in pypi wouldn't be too difficult. Especially since there's already a CI involved, the process could be automated so each tag gets pushed to pypi. I wrote the same thing for WMCore's CI, and it was just a handful of lines of code in jenkins.

**Comment by matz-e** [comment]
I was looking into it, and I don't think it's too hard with Travis.  On the order of a few lines plus time to experiment, so it probably does not differ from Jenkins that much.

**Comment by matz-e** [comment]
Big hangup: cctools needs to be installed for Lobster to work and won't make it into pypi due to the large C component that puts it out of scope. CVMFS seems better suited, reopen if you disagree :)
