### ISSUE TITLE
kill problematic workers

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#78]
Certain types of errors are caused by issues with the worker machine's configuration (see error 127 [here](http://www.crc.nd.edu/~awoodard/lobster/scale_vs_overhead_aod_1_core_workers_10_events_per_job_v21/) for example, which we think is caused because by workers landing on RH5 machines.) We already keep track of the hostname and exit code. We should intelligently kill workers that only produce failed tasks with the same exit code. @dthain, @btovar: I don't see a way to blacklist a particular worker [here](http://ccl.cse.nd.edu/software/manuals/api/html/classwork__queue_1_1WorkQueue.html), but I might be missing it. Is this functionality something you'd consider adding to Work Queue?

**Comment by klannon** [comment]
Looks like this is explained here:

https://github.com/cooperative-computing-lab/cctools/issues/664

You might want to go comment in that issue thread...

**Comment by matz-e** [comment]
So would we want to kill workers that produce a rate of more than n failed jobs per core?  Or do we have any way to find out if there is a longer running job present on the worker?  We shouldn't kill those workers…

**Comment by dthain** [comment]
Careful here -- the other components of the system assume that "reliability" means restarting and retrying things that fail.  So, if you tell a worker to die in that case, the next level up is going to restart it, and you are back to square one.

An interesting workaround might be to tell the worker "stop bothering me" by sending a job which causes it to sleep for one hour...?

**Comment by klannon** [comment]
This is a really good idea.  I think there are two different use cases though:

* Transient problem resulting in high task failure rate:  This is where we want to send some kind of "sleeper" job that will keep the node quiet for a while before it tries the node again.  Is there a way to tell WQ that you have a special task that should go to a particular worker?  Otherwise, it seems like this would need a new feature in WQ to implement.
* Terminal illness:  The node is just misconfigured and will never be helpful.  For example, if the node is missing a system library that Parrot requires, then that's never going to spontaneously get fixed, right?  In this case, it seems like you'd like for WQ to be able to communicate back to WQ pool and tell it to adjust it's submission parameters to blacklist that node.  Otherwise, you're going to need to put a sleeper job on that node permanently, preventing anyone else from using it either.  Of course , in the case that you're not using WQ pool, then the user would have to do this manually in the next worker submission.  (Still, you'd probably want to just kill the worker and put a note in the log file telling the user how to exclude that node in the future.)

Are these issues that should get entered in the cctools github?  (@dthain?  @btovar?)

Now a funny story, just because I can.  If you're busy, don't read past this point...

Back in the dark ages, before all of these fancy tools existed (i.e. when I was a grad student), there was a clever postdoc who had compiled a list of worker nodes in one of the CDF clusters that would also cause his code to crash because they were misconfigured.  He couldn't get the admins to fix the problem, so instead he wrote a script that when run, would check the node it was running on against a list of nodes that caused errors.  If it landed on a bad node, it would hold the node for as long as it could, but if it landed on a good node, it would return after only a short wait.  He would submit this script to the batch system first, and saturate it so that he could block all the bad nodes.  Then he would follow up with his actual work.

**Comment by annawoodard** [comment]
Telling transient from terminal problems.. There's the rub!



I also like the sleeper job idea, but I would vote to implement the same functionality at the master level (keep a running list of temporarily blacklisted hosts, and unblacklist them periodically?) Or at the WQ level (add a timeout option for the blacklisting feature?) 


I'm not ready to take the priority hit from running jobs that aren't directly helping me finish the task.








On Thursday Mar 12, 2015 at 3:27 PM, klannon <notifications@github.com>, wrote:
This is a really good idea.  I think there are two different use cases though:


Transient problem resulting in high task failure rate:  This is where we want to send some kind of "sleeper" job that will keep the node quiet for a while before it tries the node again.  Is there a way to tell WQ that you have a special task that should go to a particular worker?  Otherwise, it seems like this would need a new feature in WQ to implement.

Terminal illness:  The node is just misconfigured and will never be helpful.  For example, if the node is missing a system library that Parrot requires, then that's never going to spontaneously get fixed, right?  In this case, it seems like you'd like for WQ to be able to communicate back to WQ pool and tell it to adjust it's submission parameters to blacklist that node.  Otherwise, you're going to need to put a sleeper job on that node permanently, preventing anyone else from using it either.  Of course , in the case that you're not using WQ pool, then the user would have to do this manually in the next worker submission.  (Still, you'd probably want to just kill the worker and put a note in the log file telling the user how to exclude that node in the future.)

Are these issues that should get entered in the cctools github?  (@dthain?  @btovar?)


Now a funny story, just because I can.  If you're busy, don't read past this point...


Back in the dark ages, before all of these fancy tools existed (i.e. when I was a grad student), there was a clever postdoc who had compiled a list of worker nodes in one of the CDF clusters that would also cause his code to crash because they were misconfigured.  He couldn't get the admins to fix the problem, so instead he wrote a script that when run, would check the node it was running on against a list of nodes that caused errors.  If it landed on a bad node, it would hold the node for as long as it could, but if it landed on a good node, it would return after only a short wait.  He would submit this script to the batch system first, and saturate it so that he could block all the bad nodes.  Then he would follow up with his actual work.

**Comment by matz-e** [comment]
I was hoping we could have an error code specifically for, e.g., RH5 hosts.  Maybe we should `ldd` `parrot_run` and fail with a special exit code?  This could be part of a small "host-suitability" test-suite.  Then maybe we could divide failures up into transient/non-transient and act accordingly?

When we blacklist the node and work_queue_pool resubmits it, I think there are some odds the worker could end up on another system the next time.  Otherwise, if this happens too often, we should really tell the user to update their submission?  See the email-support issue…

**Comment by matz-e** [comment]
I've added a brief implementation here: 95e2f793434a1f4bc94deaa8b336092deed9827f.

Currently testing it, but it seems like jobs still get submitted to the nodes.

**Comment by matz-e** [comment]
I just re-tested this branch, and it seems to work.  But it currently only blacklists workers with missing libraries for parrot.

Adding a timeout to blacklisted workers for transient errors is something I'd rather see in WQ than having to implement it in lobster…

**Comment by dthain** [comment]
Do you mean simply that you want to pass in a time limit when something is added to the blacklist?
Or something more complicated than that?

**Comment by annawoodard** [comment]
I think passing a time limit would be all we need.

**Comment by klannon** [comment]
I agree.  I don't think we want to get into the business of generically 
managing bad workers.  I would propose the following:

1.  Make sure that our directions instruct people to submit workers with 
the appropriate requirements to ensure their workers run only on RH6 
resources.  I think there is really very little benefit to trying to 
grab the few remaining RH5 resources on campus and for most users 
(except our few 8 TeV hold-outs) the RH5 resources can't run the CMS 
code anyway.

2.  Put in this check for black listing nodes where Parrot crashes, just 
in case something slips through the above.  I think if you can't even 
run Parrot, that resources is pretty much hopeless.

Make sense?

**Comment by annawoodard** [comment]
I think passing a time limit would be all we need.

**Comment by klannon** [comment]
Well, it depends on how ambitious you are.  Are you taking requests?  
Could we have a connection between WQ and WQ Pool such that the 
blacklisted worker is killed and excluded from resubmission for some 
amount of time?

**Comment by dthain** [comment]
I'm not feeling that ambitious.:)

Let's go with a modification to the API that enables a blacklist entry to automatically expire after a certain amount of time.

**Comment by matz-e** [comment]
Sounds good.  I guess we should come up with exact criteria to temporarily blacklist workers?

**Comment by annawoodard** [comment]
> Sounds good. I guess we should come up with exact criteria to temporarily blacklist workers?

I think we should start with a simple mapping between groups of exit codes and actions. I vote that we make it as configurable as possible in the lobster configuration at first. This will allow us to test things more conveniently, and after we have a better handle on the trends, we can move it 'under the hood' if we want to. As a very simple first pass, I'd suggest allowing the user to specify a list of exit codes, with these options:
  * threshold: blacklist a worker after it has returned the given exit code this many times
  * timeout: time after which blacklisting will expire

We could also specify a default mapping for Lobster error codes. Looking through [them](https://github.com/matz-e/lobster/blob/master/doc/ErrorCodes.md), I think that blacklisting is going to be most useful for permanent configuration problems, rather than transient ones. There is a large class of transient issues for which we don't want to blacklist workers-- for example, exit code 171, which we sometimes get while the cache is warming up, but always goes away.

**Comment by annawoodard** [comment]
> Otherwise, if this happens too often, we should really tell the user to update their submission?

For far away in futureland, it would be neat to try to diff the classads from nodes that are sending back successful jobs versus those that are sending back failed jobs, and try to make suggestions about where the issue might be.
