### ISSUE TITLE
Make a copy of extra inputs.

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#84]
We currently keep a copy of the cmssw pset, but not any other extra inputs which are specified in the configuration. I think that we should do so. If there is a good reason not to, then we should at least save the full path to those files. This is related to #77, but I'd rather keep it separate.

**Comment by matz-e** [comment]
Full paths are a good default, I think.  I would save files if explicitly asked for in the configuration, otherwise our working directory might eat more space than expected.

**Comment by annawoodard** [comment]
Ok, I agree that having the working directory eat too much space would be a problem, but I'd say that 99% of the time `extra inputs` is going to be scripts or similar which are basically free to save copies of. So we should have a switch to exclude `extra inputs` if necessary, but I'd vote the default be to save them, as the potential cost of not being able to precisely reproduce a workflow could be very high.

**Comment by matz-e** [comment]
How about a conglomerate limit of 100 MB for all `extra inputs`?  If it's smaller than that, copy, otherwise put in absolute paths (and maybe copy the smallest files)?

**Comment by annawoodard** [comment]
Sounds good.

**Comment by klannon** [comment]
I'm not in favor of doing this because there might be cases where you 
would want behavior different from these assumptions.  I prefer the 
suggested solution of having a user parameter to control copying 
behavior.  Personally, I'd just make it a boolean switch, but you could 
also, I suppose, implement it according to your concept, but make it a 
variable threshold instead of 100 MB.

**Comment by matz-e** [comment]
Good point.  Boolean switch it is, for well-defined behavior.
