### ISSUE TITLE
Fix reporting for non-cmsRun jobs.

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#95]
Dashboard reporting is currently enabled by default for all cmssw-type jobs (see [here](https://github.com/matz-e/lobster/blob/master/lobster/cmssw/job.py#L230).) Non-cmsRun jobs are being reported by the master, but not updated from the worker nodes, because they do not run the python job wrapper. We should either disable reporting for non-cmsRun jobs or (preferably) fix it. This is related to #85.

**Comment by khurtado** [comment]
I'm tagging this as enhancement because we have never really supported dashboard reporting on non-cmsRun jobs properly (i.e even the Master reports non-cmsRun jobs as cmsRun, since the application name is hardcoded). Maybe a new wrapper for these kind of jobs would be better than tweaking the current one with dashboard bits. Suggestions?
I'm turning the dashboard off by default again for now (since the current default value applies it to both cmsRun and non-cmsRun jobs)

**Comment by annawoodard** [comment]
> I'm turning the dashboard off by default again for now (since the current default value applies it to both cmsRun and non-cmsRun jobs)

I think we should only turn it off for non-cmsRun jobs.

**Comment by annawoodard** [comment]
I see that it would take a little shuffling, because `cmssw_job` is set in `obtain()` instead of `__init__()`. So I'd say we have two issues here: 1) disable reporting for non-cmsRun jobs only (higher priority), and 2) fix reporting for non-cmsRun jobs (enhancement).

I don't like putting even more switches in the configuration file, but maybe the most straightforward thing for 1) is to ask the user for the application type? Then we can pass that onto the dashboard.

> Maybe a new wrapper for these kind of jobs would be better than tweaking the current one with dashboard bits. Suggestions?

I think @matz-e's [suggestion](https://github.com/matz-e/lobster/issues/85#issuecomment-88054321) in #85 is relevant here.

**Comment by klannon** [comment]
Actually, can I ask that we consider this a bug that needs fixing. 
Dashboard reporting needs to be on by default.  I know this may seem 
strange, but we need to make sure that we report to the dashboard all of 
our site activity.  It has implications for when we make claims about 
Lobster's success and our site capabilities.  If we "fix" this by 
turning dashboard reporting off by default, then most users will run 
without it and we won't have any record of how much we can do with 
Lobster at ND.

**Comment by khurtado** [comment]
>I see that it would take a little shuffling, because cmssw_job is set in obtain() instead of __init__(). So I'd >say we have two issues here: 1) disable reporting for non-cmsRun jobs only (higher priority), and 2) fix >reporting for non-cmsRun jobs (enhancement).
I was just writing the same... notice the cmssw_job in obtain() is checked by label. Do we have .yaml configurations running cmsRun and non-cmsRun jobs on the same task (one type per label)?

>I don't like putting even more switches in the configuration file, but maybe the most straightforward thing >for 1) is to ask the user for the application type? Then we can pass that onto the dashboard.

If we can run cmsRun and non-cmsRun jobs on the same task, then this application type should be added per each task/label, or specified on "task defaults". I agree this would be the more straightforward solution, but it would be better to handle it internally in the class rather than trusting the users to provide that info. Users are already specifying a "cmssw config" for cmsRun jobs, aren't they?

**Comment by matz-e** [comment]
As I tried to mention in the issue that Anna linked, I think the way forward here is to slightly alter the wrapper to have the PSet be optional and allow for a substitute command instead of `cmsRun`.  The dashboard actually allows for different executables, and that's what crab is doing, IIRC.  Then we could also remove the switches that allow you to disable the dashboard at the moment.

**Comment by matz-e** [comment]
@khurtado yes, all that could probably need some cleaning up.  We could allow for a `cmssw config` and a `executable` (which defaults to `cmsRun`).  I think it would be preferable to have one wrapper "fits all" eventually. and not allow to swap that out.

**Comment by khurtado** [comment]
@matz-e Sounds good, although... besides dashboard issues. If we allow a cmssw config and an executable, would that imply the bash wrapper using the job.py wrapper for cmsRun and another new generic python wrapper for non-cmsRun jobs (which would be called if the executable is not cmsRun)?

**Comment by matz-e** [comment]
@khurtado, I would leave the wrapper and adapt `job.py` to allow generic executables to be run, to re-use as much as possible.  The wrapper is basically only there to create the CMS environment.  I can think of cases where an alternative wrapper could be useful (running from a CMSSW area in AFS, for example), but I'm not sure how this should be presented to the user, if at all.

**Comment by annawoodard** [comment]
> The dashboard actually allows for different executables, and that's what crab is doing, IIRC. 

Yes this is correct.

> Then we could also remove the switches that allow you to disable the dashboard at the moment.

I think we should leave the disable switch in, or take out and add one that allows you to set the analysis type. In that case the default would be lobster, but we could change it to lobster-test or something like that if needed. I've seen the dashboard people asking CRAB devs to distinguish testing from analysis jobs.
